# Site settings
course_name: Natural Language Processing - A Machine Learning Perspective
course_description: "This online course is based on the recently released textbook, Natural Language Processing - a Machine Learning Perspective, written by Dr. Yue Zhang & Dr. Zhiyang Teng and published by Cambridge University Press. The course is taught in Chinese, English version of the class will be updated in future releases. Professor Yue Zhang is the principal inverstigator of the Text Intelligence Lab, Westlake University, and a well-known NLP researcher. You may find more detailed information at his personal page or Google Scholar. Course updates are in progress on our bilibili account, WestlakeNLP, do not hesitate to follow us! In this page, we will keep updating course slides."
course_semester: "Spring 2023"

baseurl: "/nlpml" # the subpath of your site, e.g. /blog/
url: "https://westlakenlp.github.io" # the base hostname & protocol for your site

schoolname: "Westlake University"
schoolurl: "https://westlake.edu.cn"
twitter_username: NlpWestlake

address: |
    School of Engineering
    Westlake University
    Hangzhou
    Zhejiang
    China
# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
